### ISSUE TITLE
the effect of min_length in minhash_spark.py/minhash.py

### ISSUE THREAD

**Issue by Jason3900** [ChenghaoMou/text-dedup#77]
Appreciate your efforts on this excellent work!
I found that there's a ngram encoding step is processed before hashing in minhash_spark.py. If the length of a doc is below the min_length, then it will output an empty list. After hashing, it will be a list of MAX_HASH values, which means all the low-length docs will have the same signature after generate_hash_values. Will they be deduplicated to only one in the end (regardless of the content but only length-based)?
Looking forward to your reply~

**Comment by ChenghaoMou** [comment]
Thanks for the question.

First, yes. Short text is effectively dropped if they are below the threshold, except one, to be more precise. I will make it more explicit and clear in the code.

Previously, they were filtered out with an additional filter function call but later merged into the hashing function to fuse more operations together — calculating ngrams twice or passing ngrams around is expensive. But feel free to modify the code to suit your use case.

**Comment by Jason3900** [comment]
I see. I'm wondering if you can point it out in the arguments to make it more clear. At the first glance, I might think the low-length documents will not be participated in the minhash deduplication process as the typicality of the signatures of low-length docs and high-length docs may vary which may introduce some bias, to my limited knowledge.
https://github.com/ChenghaoMou/text-dedup/blob/b665324b0ca776d72fc7d40d39c623b9c451b1c4/text_dedup/minhash_spark.py#L364

And I'm also curious about why rdd is used instead of spark's dataframe. Is it because some operation relies on low-level rdd which cannot be implemented with df?

**Comment by ChenghaoMou** [comment]
Right. It actually was called out for the non-spark version in [text_dedup/utils/add_args.py](https://github.com/ChenghaoMou/text-dedup/blob/b665324b0ca776d72fc7d40d39c623b9c451b1c4/text_dedup/utils/add_args.py#L112). I just need to update the spark one #78.

RDD is used for mainly the functional programming interface instead of constructing UDFs. But it is becoming more and more Dataframe oriented (e.g. `bigcode-v2/intra_dedup.py`). I just haven't got the time to merge those changes in yet.

**Comment by Jason3900** [comment]
Thanks! I got it. Appreciate your help. Looking forward to future progress.
