### ISSUE TITLE
how about make a ray executor to deduplication

### ISSUE THREAD

**Issue by simplew2011** [ChenghaoMou/text-dedup#81]
- https://github.com/ChenghaoMou/text-dedup/blob/main/text_dedup/minhash_spark.py
- reference：https://github.com/alibaba/data-juicer/blob/main/data_juicer/core/ray_executor.py
- Ray is simpler and faster than Spark

**Comment by ChenghaoMou** [comment]
Thanks for the suggestion!

AFAIK, there is no comparable graph processing library for Ray, making it less ideal when processing large scale datasets for clustering, which can be a bottleneck for minhash deduplication. 

In data juicer's code, the clustering is done with a union find algorithm executed in one place, which is based on an older version of BigCode's codebase. We have moved away from that because of the scalability issue.
